/* Configuration for spark_argon2id generated by Alire */
#ifndef SPARK_ARGON2ID_CONFIG_H
#define SPARK_ARGON2ID_CONFIG_H

#define CRATE_VERSION "1.1.0"
#define CRATE_NAME "spark_argon2id"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
