name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and Test (Production 1 GiB)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alire
        uses: alire-project/setup-alire@v2
        with:
          toolchain: gnat_native gprbuild

      - name: Display environment
        run: |
          echo "=== Alire Version ==="
          alr version
          echo ""
          echo "=== Toolchain ==="
          alr toolchain
          echo ""

      - name: "Build library (Production mode 1 GiB)"
        run: alr build -- -XBUILD_MODE=release -XPROOF=false

      - name: Run smoke test
        run: make test

      - name: Run RFC 9106 KAT tests
        run: make kat

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            obj/
            lib/
          retention-days: 7

  verify:
    name: SPARK Formal Verification
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alire
        uses: alire-project/setup-alire@v2
        with:
          toolchain: gnat_native gprbuild

      - name: Install GNATprove dependency
        run: alr build --validation

      - name: Run SPARK verification
        run: alr exec -- gnatprove -P spark_argon2id.gpr -XPROOF=true --level=2 --timeout=60 --report=all || true

      - name: Upload proof results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: proof-results
          path: obj/gnatprove/
          retention-days: 7
